export const docsRouteComponentSlugs = [
  "alert",
  "badge",
  "banner",
  "breadcrumbs",
  "button",
  "button-group",
  "calendar",
  "card",
  "code-block",
  "coachmark-tour",
  "command-palette",
  "data-view-toolbar",
  "divider",
  "dialog",
  "dropzone",
  "email-input",
  "empty-state",
  "error-text",
  "form",
  "form-field",
  "form-row",
  "helper-text",
  "icon",
  "icon-button",
  "input",
  "json-viewer",
  "kanban-board",
  "layout",
  "layout-content",
  "layout-header",
  "link",
  "listbox",
  "markdown-editor",
  "menu-item",
  "notification-center",
  "option",
  "provider",
  "radio",
  "range",
  "search",
  "segmented-control",
  "spinner",
  "split-button",
  "stack",
  "stepper",
  "tabs",
  "tel-input",
  "textarea",
  "url-input"
] as const;

export const componentDependencySlugs: Record<string, string[]> = {
  autocomplete: ["listbox", "option"],
  banner: ["icon-button"],
  calendar: ["icon-button"],
  combobox: ["listbox", "option"],
  "command-palette": ["dialog", "icon-button", "listbox", "option", "search"],
  "context-menu": ["menu"],
  "data-grid": ["input", "select", "switch"],
  "data-table": ["button", "icon", "icon-button", "input", "pagination", "search", "select", "switch", "tooltip"],
  "date-picker": ["calendar", "icon-button"],
  "date-range-picker": ["calendar", "icon-button"],
  "date-time-picker": ["date-picker", "time-input"],
  dialog: ["icon-button"],
  drawer: ["icon-button"],
  "dropdown-menu": ["menu"],
  dropzone: ["button", "chip", "icon"],
  "empty-search-results": ["icon"],
  "field-array": ["button", "icon-button"],
  "file-input": ["button", "chip", "icon"],
  "filter-builder": ["button", "date-input", "fieldset", "form-field", "input", "number-input", "select"],
  "icon-button": ["button", "icon"],
  "inline-edit": ["button"],
  input: ["icon"],
  "multi-select": ["listbox", "option"],
  "password-input": ["icon"],
  "sortable-list": ["icon-button"],
  "split-button": ["button", "icon", "menu"],
  stepper: ["icon"],
  tabs: ["form-field", "select"],
  "tag-input": ["listbox", "option"],
  toast: ["icon-button"],
  "transfer-list": ["button", "form-field"],
  "tree-grid": ["data-table"],
  "workspace-switcher": ["icon"]
};

export const previewDependencySlugs: Record<string, string[]> = {
  "activity-feed": ["activity-item", "avatar"],
  "activity-item": ["activity-feed", "avatar"],
  "button-group": ["button"],
  "coachmark-tour": ["badge", "card"],
  "command-bar": ["button"],
  "combobox": ["option"],
  "data-view-toolbar": ["badge", "button", "button-group", "search", "segmented-control"],
  "description-item": ["description-list"],
  "description-list": ["description-item"],
  "fieldset": ["checkbox"],
  "form-field": ["input"],
  "layout": ["layout-header", "layout-content", "card"],
  "layout-content": ["card"],
  "layout-header": ["breadcrumbs"],
  "menubar": ["button"],
  "multi-select": ["option"],
  "navigation-rail": ["navigation-rail-item", "icon"],
  "navigation-rail-item": ["icon"],
  "notification-center": ["activity-item", "avatar", "badge", "button"],
  "page-header": ["breadcrumbs", "badge", "button"],
  "panel-inspector": ["badge", "button", "description-item", "description-list"],
  "provider": ["card"],
  "side-nav": ["side-nav-item"],
  "side-nav-item": ["side-nav-item"],
  "splitter": ["splitter-panel"],
  "stack": ["badge", "button"],
  "timeline": ["timeline-item"],
  "timeline-item": ["timeline"],
  "toolbar": ["button", "button-group"],
  "transfer-list": ["option"],
  "tree-item": ["tree-item"],
  "tree-view": ["tree-item"]
};
