export const docsRouteComponentSlugs = [
  "alert",
  "badge",
  "breadcrumbs",
  "button",
  "calendar",
  "card",
  "code-block",
  "command-palette",
  "dropzone",
  "email-input",
  "empty-state",
  "form",
  "form-field",
  "form-row",
  "icon",
  "input",
  "layout",
  "layout-content",
  "layout-header",
  "provider",
  "search",
  "segmented-control",
  "spinner",
  "stack",
  "stepper",
  "tabs"
] as const;

export const previewDependencySlugs: Record<string, string[]> = {
  "activity-feed": ["activity-item", "avatar"],
  "activity-item": ["activity-feed", "avatar"],
  "button-group": ["button"],
  "command-bar": ["button"],
  "combobox": ["option"],
  "description-item": ["description-list"],
  "description-list": ["description-item"],
  "fieldset": ["checkbox"],
  "form-field": ["input"],
  "layout": ["layout-header", "layout-content", "card"],
  "layout-content": ["card"],
  "layout-header": ["breadcrumbs"],
  "menubar": ["button"],
  "multi-select": ["option"],
  "navigation-rail": ["navigation-rail-item", "icon"],
  "navigation-rail-item": ["icon"],
  "page-header": ["breadcrumbs", "badge", "button"],
  "panel-inspector": ["badge", "button", "description-item", "description-list"],
  "provider": ["card"],
  "side-nav": ["side-nav-item"],
  "side-nav-item": ["side-nav-item"],
  "splitter": ["splitter-panel"],
  "stack": ["badge", "button"],
  "timeline": ["timeline-item"],
  "timeline-item": ["timeline"],
  "toolbar": ["button", "button-group"],
  "transfer-list": ["option"],
  "tree-item": ["tree-item"],
  "tree-view": ["tree-item"]
};
