// AUTO-GENERATED BY npm run generate:wrappers. DO NOT EDIT MANUALLY.
import * as React from "react";
import { createComponent } from "@lit/react";

import {
  EmbButton as EmbButtonElement,
  EmbButtonGroup as EmbButtonGroupElement,
  EmbChip as EmbChipElement,
  EmbIconButton as EmbIconButtonElement,
  EmbCard as EmbCardElement,
  EmbCalendar as EmbCalendarElement,
  EmbBadge as EmbBadgeElement,
  EmbDivider as EmbDividerElement,
  EmbSpinner as EmbSpinnerElement,
  EmbAlert as EmbAlertElement,
  EmbActivityFeed as EmbActivityFeedElement,
  EmbActivityItem as EmbActivityItemElement,
  EmbAutocomplete as EmbAutocompleteElement,
  EmbAvatar as EmbAvatarElement,
  EmbProgress as EmbProgressElement,
  EmbMeter as EmbMeterElement,
  EmbBreadcrumbs as EmbBreadcrumbsElement,
  EmbSkeleton as EmbSkeletonElement,
  EmbStepper as EmbStepperElement,
  EmbLink as EmbLinkElement,
  EmbFieldset as EmbFieldsetElement,
  EmbFormField as EmbFormFieldElement,
  EmbHelperText as EmbHelperTextElement,
  EmbErrorText as EmbErrorTextElement,
  EmbRange as EmbRangeElement,
  EmbFileInput as EmbFileInputElement,
  EmbFilterBuilder as EmbFilterBuilderElement,
  EmbPagination as EmbPaginationElement,
  EmbPageHeader as EmbPageHeaderElement,
  EmbPanelInspector as EmbPanelInspectorElement,
  EmbDataTable as EmbDataTableElement,
  EmbEmptyState as EmbEmptyStateElement,
  EmbEmptySearchResults as EmbEmptySearchResultsElement,
  EmbIcon as EmbIconElement,
  EmbCodeBlock as EmbCodeBlockElement,
  EmbCommandBar as EmbCommandBarElement,
  EmbCommandPalette as EmbCommandPaletteElement,
  EmbContextMenu as EmbContextMenuElement,
  EmbDatePicker as EmbDatePickerElement,
  EmbDateRangePicker as EmbDateRangePickerElement,
  EmbDateTimePicker as EmbDateTimePickerElement,
  EmbListbox as EmbListboxElement,
  EmbDescriptionItem as EmbDescriptionItemElement,
  EmbDescriptionList as EmbDescriptionListElement,
  EmbMenu as EmbMenuElement,
  EmbMenuItem as EmbMenuItemElement,
  EmbMultiSelect as EmbMultiSelectElement,
  EmbTagInput as EmbTagInputElement,
  EmbNumberInput as EmbNumberInputElement,
  EmbSearch as EmbSearchElement,
  EmbSplitter as EmbSplitterElement,
  EmbSplitterPanel as EmbSplitterPanelElement,
  EmbSegmentedControl as EmbSegmentedControlElement,
  EmbCombobox as EmbComboboxElement,
  EmbDateInput as EmbDateInputElement,
  EmbTimeInput as EmbTimeInputElement,
  EmbRatingInput as EmbRatingInputElement,
  EmbToast as EmbToastElement,
  EmbToastRegion as EmbToastRegionElement,
  EmbTooltip as EmbTooltipElement,
  EmbToolbar as EmbToolbarElement,
  EmbPopover as EmbPopoverElement,
  EmbDropdownMenu as EmbDropdownMenuElement,
  EmbDropzone as EmbDropzoneElement,
  EmbDrawer as EmbDrawerElement,
  EmbInput as EmbInputElement,
  EmbInlineEdit as EmbInlineEditElement,
  EmbEmailInput as EmbEmailInputElement,
  EmbPasswordInput as EmbPasswordInputElement,
  EmbOption as EmbOptionElement,
  EmbMenubar as EmbMenubarElement,
  EmbNavigationRail as EmbNavigationRailElement,
  EmbNavigationRailItem as EmbNavigationRailItemElement,
  EmbTelInput as EmbTelInputElement,
  EmbUrlInput as EmbUrlInputElement,
  EmbColorInput as EmbColorInputElement,
  EmbCheckbox as EmbCheckboxElement,
  EmbSelect as EmbSelectElement,
  EmbRadio as EmbRadioElement,
  EmbDialog as EmbDialogElement,
  EmbTextarea as EmbTextareaElement,
  EmbSwitch as EmbSwitchElement,
  EmbTabs as EmbTabsElement,
  EmbAccordion as EmbAccordionElement,
  EmbTreeItem as EmbTreeItemElement,
  EmbTreeView as EmbTreeViewElement,
  EmbStatCard as EmbStatCardElement,
  EmbTimeline as EmbTimelineElement,
  EmbTimelineItem as EmbTimelineItemElement,
  EmbTransferList as EmbTransferListElement,
  EmbSideNav as EmbSideNavElement,
  EmbSideNavItem as EmbSideNavItemElement,
} from "emberline-ui-core";
export { clearToasts, dismissToast, ensureToastRegion, showToast } from "emberline-ui-core";
import "emberline-ui-core/register";

export const EmbButton = createComponent({
  react: React,
  tagName: "emb-button",
  elementClass: EmbButtonElement
});

export const EmbButtonGroup = createComponent({
  react: React,
  tagName: "emb-button-group",
  elementClass: EmbButtonGroupElement
});

export const EmbChip = createComponent({
  react: React,
  tagName: "emb-chip",
  elementClass: EmbChipElement
});

export const EmbIconButton = createComponent({
  react: React,
  tagName: "emb-icon-button",
  elementClass: EmbIconButtonElement
});

export const EmbCard = createComponent({
  react: React,
  tagName: "emb-card",
  elementClass: EmbCardElement
});

export const EmbCalendar = createComponent({
  react: React,
  tagName: "emb-calendar",
  elementClass: EmbCalendarElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbBadge = createComponent({
  react: React,
  tagName: "emb-badge",
  elementClass: EmbBadgeElement
});

export const EmbDivider = createComponent({
  react: React,
  tagName: "emb-divider",
  elementClass: EmbDividerElement
});

export const EmbSpinner = createComponent({
  react: React,
  tagName: "emb-spinner",
  elementClass: EmbSpinnerElement
});

export const EmbAlert = createComponent({
  react: React,
  tagName: "emb-alert",
  elementClass: EmbAlertElement
});

export const EmbActivityFeed = createComponent({
  react: React,
  tagName: "emb-activity-feed",
  elementClass: EmbActivityFeedElement
});

export const EmbActivityItem = createComponent({
  react: React,
  tagName: "emb-activity-item",
  elementClass: EmbActivityItemElement
});

export const EmbAutocomplete = createComponent({
  react: React,
  tagName: "emb-autocomplete",
  elementClass: EmbAutocompleteElement,
  events: {
    onChange: "change",
    onInput: "input",
    onSuggestionSelect: "suggestion-select"
  }
});

export const EmbAvatar = createComponent({
  react: React,
  tagName: "emb-avatar",
  elementClass: EmbAvatarElement
});

export const EmbProgress = createComponent({
  react: React,
  tagName: "emb-progress",
  elementClass: EmbProgressElement
});

export const EmbMeter = createComponent({
  react: React,
  tagName: "emb-meter",
  elementClass: EmbMeterElement
});

export const EmbBreadcrumbs = createComponent({
  react: React,
  tagName: "emb-breadcrumbs",
  elementClass: EmbBreadcrumbsElement
});

export const EmbSkeleton = createComponent({
  react: React,
  tagName: "emb-skeleton",
  elementClass: EmbSkeletonElement
});

export const EmbStepper = createComponent({
  react: React,
  tagName: "emb-stepper",
  elementClass: EmbStepperElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbLink = createComponent({
  react: React,
  tagName: "emb-link",
  elementClass: EmbLinkElement
});

export const EmbFieldset = createComponent({
  react: React,
  tagName: "emb-fieldset",
  elementClass: EmbFieldsetElement
});

export const EmbFormField = createComponent({
  react: React,
  tagName: "emb-form-field",
  elementClass: EmbFormFieldElement
});

export const EmbHelperText = createComponent({
  react: React,
  tagName: "emb-helper-text",
  elementClass: EmbHelperTextElement
});

export const EmbErrorText = createComponent({
  react: React,
  tagName: "emb-error-text",
  elementClass: EmbErrorTextElement
});

export const EmbRange = createComponent({
  react: React,
  tagName: "emb-range",
  elementClass: EmbRangeElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbFileInput = createComponent({
  react: React,
  tagName: "emb-file-input",
  elementClass: EmbFileInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbFilterBuilder = createComponent({
  react: React,
  tagName: "emb-filter-builder",
  elementClass: EmbFilterBuilderElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbPagination = createComponent({
  react: React,
  tagName: "emb-pagination",
  elementClass: EmbPaginationElement,
  events: {
    onChange: "change"
  }
});

export const EmbPageHeader = createComponent({
  react: React,
  tagName: "emb-page-header",
  elementClass: EmbPageHeaderElement
});

export const EmbPanelInspector = createComponent({
  react: React,
  tagName: "emb-panel-inspector",
  elementClass: EmbPanelInspectorElement
});

export const EmbDataTable = createComponent({
  react: React,
  tagName: "emb-data-table",
  elementClass: EmbDataTableElement,
  events: {
    onPageChange: "page-change",
    onSearchChange: "search-change",
    onSortChange: "sort-change"
  }
});

export const EmbEmptyState = createComponent({
  react: React,
  tagName: "emb-empty-state",
  elementClass: EmbEmptyStateElement
});

export const EmbEmptySearchResults = createComponent({
  react: React,
  tagName: "emb-empty-search-results",
  elementClass: EmbEmptySearchResultsElement
});

export const EmbIcon = createComponent({
  react: React,
  tagName: "emb-icon",
  elementClass: EmbIconElement
});

export const EmbCodeBlock = createComponent({
  react: React,
  tagName: "emb-code-block",
  elementClass: EmbCodeBlockElement
});

export const EmbCommandBar = createComponent({
  react: React,
  tagName: "emb-command-bar",
  elementClass: EmbCommandBarElement
});

export const EmbCommandPalette = createComponent({
  react: React,
  tagName: "emb-command-palette",
  elementClass: EmbCommandPaletteElement,
  events: {
    onCancel: "cancel",
    onChange: "change",
    onClose: "close",
    onCommandSelect: "command-select",
    onInput: "input"
  }
});

export const EmbContextMenu = createComponent({
  react: React,
  tagName: "emb-context-menu",
  elementClass: EmbContextMenuElement,
  events: {
    onToggle: "toggle"
  }
});

export const EmbDatePicker = createComponent({
  react: React,
  tagName: "emb-date-picker",
  elementClass: EmbDatePickerElement,
  events: {
    onChange: "change",
    onInput: "input",
    onToggle: "toggle"
  }
});

export const EmbDateRangePicker = createComponent({
  react: React,
  tagName: "emb-date-range-picker",
  elementClass: EmbDateRangePickerElement,
  events: {
    onChange: "change",
    onInput: "input",
    onToggle: "toggle"
  }
});

export const EmbDateTimePicker = createComponent({
  react: React,
  tagName: "emb-date-time-picker",
  elementClass: EmbDateTimePickerElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbListbox = createComponent({
  react: React,
  tagName: "emb-listbox",
  elementClass: EmbListboxElement
});

export const EmbDescriptionItem = createComponent({
  react: React,
  tagName: "emb-description-item",
  elementClass: EmbDescriptionItemElement
});

export const EmbDescriptionList = createComponent({
  react: React,
  tagName: "emb-description-list",
  elementClass: EmbDescriptionListElement
});

export const EmbMenu = createComponent({
  react: React,
  tagName: "emb-menu",
  elementClass: EmbMenuElement
});

export const EmbMenuItem = createComponent({
  react: React,
  tagName: "emb-menu-item",
  elementClass: EmbMenuItemElement
});

export const EmbMultiSelect = createComponent({
  react: React,
  tagName: "emb-multi-select",
  elementClass: EmbMultiSelectElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbTagInput = createComponent({
  react: React,
  tagName: "emb-tag-input",
  elementClass: EmbTagInputElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbNumberInput = createComponent({
  react: React,
  tagName: "emb-number-input",
  elementClass: EmbNumberInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbSearch = createComponent({
  react: React,
  tagName: "emb-search",
  elementClass: EmbSearchElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbSplitter = createComponent({
  react: React,
  tagName: "emb-splitter",
  elementClass: EmbSplitterElement,
  events: {
    onPanelResize: "panel-resize"
  }
});

export const EmbSplitterPanel = createComponent({
  react: React,
  tagName: "emb-splitter-panel",
  elementClass: EmbSplitterPanelElement
});

export const EmbSegmentedControl = createComponent({
  react: React,
  tagName: "emb-segmented-control",
  elementClass: EmbSegmentedControlElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbCombobox = createComponent({
  react: React,
  tagName: "emb-combobox",
  elementClass: EmbComboboxElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbDateInput = createComponent({
  react: React,
  tagName: "emb-date-input",
  elementClass: EmbDateInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbTimeInput = createComponent({
  react: React,
  tagName: "emb-time-input",
  elementClass: EmbTimeInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbRatingInput = createComponent({
  react: React,
  tagName: "emb-rating-input",
  elementClass: EmbRatingInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbToast = createComponent({
  react: React,
  tagName: "emb-toast",
  elementClass: EmbToastElement,
  events: {
    onClose: "close"
  }
});

export const EmbToastRegion = createComponent({
  react: React,
  tagName: "emb-toast-region",
  elementClass: EmbToastRegionElement,
  events: {
    onToastShow: "toast-show",
    onToastRemove: "toast-remove"
  }
});

export const EmbTooltip = createComponent({
  react: React,
  tagName: "emb-tooltip",
  elementClass: EmbTooltipElement
});

export const EmbToolbar = createComponent({
  react: React,
  tagName: "emb-toolbar",
  elementClass: EmbToolbarElement
});

export const EmbPopover = createComponent({
  react: React,
  tagName: "emb-popover",
  elementClass: EmbPopoverElement,
  events: {
    onToggle: "toggle"
  }
});

export const EmbDropdownMenu = createComponent({
  react: React,
  tagName: "emb-dropdown-menu",
  elementClass: EmbDropdownMenuElement,
  events: {
    onToggle: "toggle"
  }
});

export const EmbDropzone = createComponent({
  react: React,
  tagName: "emb-dropzone",
  elementClass: EmbDropzoneElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbDrawer = createComponent({
  react: React,
  tagName: "emb-drawer",
  elementClass: EmbDrawerElement,
  events: {
    onClose: "close"
  }
});

export const EmbInput = createComponent({
  react: React,
  tagName: "emb-input",
  elementClass: EmbInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbInlineEdit = createComponent({
  react: React,
  tagName: "emb-inline-edit",
  elementClass: EmbInlineEditElement,
  events: {
    onCancel: "cancel",
    onChange: "change",
    onInput: "input",
    onToggle: "toggle"
  }
});

export const EmbEmailInput = createComponent({
  react: React,
  tagName: "emb-email-input",
  elementClass: EmbEmailInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbPasswordInput = createComponent({
  react: React,
  tagName: "emb-password-input",
  elementClass: EmbPasswordInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbOption = createComponent({
  react: React,
  tagName: "emb-option",
  elementClass: EmbOptionElement
});

export const EmbMenubar = createComponent({
  react: React,
  tagName: "emb-menubar",
  elementClass: EmbMenubarElement
});

export const EmbNavigationRail = createComponent({
  react: React,
  tagName: "emb-navigation-rail",
  elementClass: EmbNavigationRailElement
});

export const EmbNavigationRailItem = createComponent({
  react: React,
  tagName: "emb-navigation-rail-item",
  elementClass: EmbNavigationRailItemElement
});

export const EmbTelInput = createComponent({
  react: React,
  tagName: "emb-tel-input",
  elementClass: EmbTelInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbUrlInput = createComponent({
  react: React,
  tagName: "emb-url-input",
  elementClass: EmbUrlInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbColorInput = createComponent({
  react: React,
  tagName: "emb-color-input",
  elementClass: EmbColorInputElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbCheckbox = createComponent({
  react: React,
  tagName: "emb-checkbox",
  elementClass: EmbCheckboxElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbSelect = createComponent({
  react: React,
  tagName: "emb-select",
  elementClass: EmbSelectElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbRadio = createComponent({
  react: React,
  tagName: "emb-radio",
  elementClass: EmbRadioElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbDialog = createComponent({
  react: React,
  tagName: "emb-dialog",
  elementClass: EmbDialogElement,
  events: {
    onClose: "close",
    onCancel: "cancel"
  }
});

export const EmbTextarea = createComponent({
  react: React,
  tagName: "emb-textarea",
  elementClass: EmbTextareaElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbSwitch = createComponent({
  react: React,
  tagName: "emb-switch",
  elementClass: EmbSwitchElement,
  events: {
    onInput: "input",
    onChange: "change"
  }
});

export const EmbTabs = createComponent({
  react: React,
  tagName: "emb-tabs",
  elementClass: EmbTabsElement,
  events: {
    onChange: "change"
  }
});

export const EmbAccordion = createComponent({
  react: React,
  tagName: "emb-accordion",
  elementClass: EmbAccordionElement,
  events: {
    onToggle: "toggle"
  }
});

export const EmbTreeItem = createComponent({
  react: React,
  tagName: "emb-tree-item",
  elementClass: EmbTreeItemElement
});

export const EmbTreeView = createComponent({
  react: React,
  tagName: "emb-tree-view",
  elementClass: EmbTreeViewElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbStatCard = createComponent({
  react: React,
  tagName: "emb-stat-card",
  elementClass: EmbStatCardElement
});

export const EmbTimeline = createComponent({
  react: React,
  tagName: "emb-timeline",
  elementClass: EmbTimelineElement
});

export const EmbTimelineItem = createComponent({
  react: React,
  tagName: "emb-timeline-item",
  elementClass: EmbTimelineItemElement
});

export const EmbTransferList = createComponent({
  react: React,
  tagName: "emb-transfer-list",
  elementClass: EmbTransferListElement,
  events: {
    onChange: "change",
    onInput: "input"
  }
});

export const EmbSideNav = createComponent({
  react: React,
  tagName: "emb-side-nav",
  elementClass: EmbSideNavElement
});

export const EmbSideNavItem = createComponent({
  react: React,
  tagName: "emb-side-nav-item",
  elementClass: EmbSideNavItemElement
});
