// AUTO-GENERATED BY npm run generate:wrappers. DO NOT EDIT MANUALLY.
import { defineComponent, h, type PropType } from "vue";

import type {
  ButtonGroupOrientation,
  ButtonType,
  ButtonVariant,
  ChipTone,
  CommandPaletteCommand,
  DataTableColumn,
  DataTableRow,
  DataTableSortDirection,
  LucideIconName,
  SegmentedControlOption,
  SkeletonVariant,
  SplitterOrientation,
  StepperOrientation,
  StepperStep,
  ToastPlacement,
  ToolbarOrientation
} from "emberline-ui-core";
export { clearToasts, dismissToast, ensureToastRegion, showToast } from "emberline-ui-core";
import "emberline-ui-core/register";

type InputHost = HTMLElement & { value: string };
type CheckboxHost = HTMLElement & { checked: boolean };
type SelectHost = HTMLElement & { value: string };
type OpenHost = HTMLElement & { open: boolean };
type FileInputHost = HTMLElement & { files: FileList | null };
type PageHost = HTMLElement & { currentPage: number };
type SearchQueryHost = HTMLElement & { searchQuery: string };

export const EmbButton = defineComponent({
  name: "EmbButton",
  props: {
    disabled: { type: Boolean, default: false },
    iconOnly: { type: Boolean, default: false },
    type: { type: String as PropType<ButtonType>, default: "button" },
    variant: { type: String as PropType<ButtonVariant>, default: "solid" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-button",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              iconOnly: props.iconOnly || undefined,
              type: props.type,
              variant: props.variant,
            },
            slots
          );
  }
});

export const EmbButtonGroup = defineComponent({
  name: "EmbButtonGroup",
  props: {
    attached: { type: Boolean, default: false },
    orientation: { type: String as PropType<ButtonGroupOrientation>, default: "horizontal" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-button-group",
            {
              ...attrs,
              attached: props.attached || undefined,
              orientation: props.orientation,
            },
            slots.default?.()
          );
  }
});

export const EmbChip = defineComponent({
  name: "EmbChip",
  props: {
    tone: { type: String as PropType<ChipTone>, default: "neutral" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-chip",
            {
              ...attrs,
              tone: props.tone,
            },
            slots.default?.()
          );
  }
});

export const EmbIconButton = defineComponent({
  name: "EmbIconButton",
  props: {
    disabled: { type: Boolean, default: false },
    label: { type: String, default: "" },
    name: { type: String as PropType<LucideIconName | string>, default: "" },
    size: { type: Number, default: 16 },
    strokeWidth: { type: Number, default: 2 },
    type: { type: String as PropType<ButtonType>, default: "button" }
  },
  setup(props, { attrs }) {
    return () =>
          h("emb-icon-button", {
              ...attrs,
              disabled: props.disabled || undefined,
              label: props.label || undefined,
              name: props.name,
              size: props.size,
              "stroke-width": props.strokeWidth,
              type: props.type,
          });
  }
});

export const EmbCard = defineComponent({
  name: "EmbCard",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "emb-card",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const EmbCalendar = defineComponent({
  name: "EmbCalendar",
  props: {
    disabled: { type: Boolean, default: false },
    endValue: { type: String, default: "" },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    month: { type: String, default: "" },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    range: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    startValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-calendar", {
              ...attrs,
              disabled: props.disabled || undefined,
              "end-value": props.endValue || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              month: props.month || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              range: props.range || undefined,
              required: props.required || undefined,
              "start-value": props.startValue || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbBadge = defineComponent({
  name: "EmbBadge",
  props: {
    tone: { type: String as PropType<"neutral" | "accent" | "success">, default: "neutral" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-badge",
            {
              ...attrs,
              tone: props.tone,
            },
            slots.default?.()
          );
  }
});

export const EmbDivider = defineComponent({
  name: "EmbDivider",
  setup(_, { attrs }) {
    return () =>
          h("emb-divider", {
              ...attrs,
          });
  }
});

export const EmbSpinner = defineComponent({
  name: "EmbSpinner",
  setup(_, { attrs }) {
    return () =>
          h("emb-spinner", {
              ...attrs,
          });
  }
});

export const EmbAlert = defineComponent({
  name: "EmbAlert",
  props: {
    tone: { type: String as PropType<"info" | "success" | "warning" | "danger">, default: "info" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-alert",
            {
              ...attrs,
              tone: props.tone,
            },
            slots.default?.()
          );
  }
});

export const EmbAvatar = defineComponent({
  name: "EmbAvatar",
  props: {
    alt: { type: String, default: "" },
    name: { type: String, default: "" },
    src: { type: String, default: "" }
  },
  setup(props, { attrs }) {
    return () =>
          h("emb-avatar", {
              ...attrs,
              alt: props.alt || undefined,
              name: props.name || undefined,
              src: props.src || undefined,
          });
  }
});

export const EmbProgress = defineComponent({
  name: "EmbProgress",
  props: {
    max: { type: Number, default: 100 },
    value: { type: Number, default: 0 }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-progress",
            {
              ...attrs,
              max: props.max,
              value: props.value,
            },
            slots.default?.()
          );
  }
});

export const EmbMeter = defineComponent({
  name: "EmbMeter",
  props: {
    high: { type: Number, default: 100 },
    low: { type: Number, default: 0 },
    max: { type: Number, default: 100 },
    min: { type: Number, default: 0 },
    optimum: { type: Number, default: 100 },
    value: { type: Number, default: 0 }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-meter",
            {
              ...attrs,
              high: props.high,
              low: props.low,
              max: props.max,
              min: props.min,
              optimum: props.optimum,
              value: props.value,
            },
            slots.default?.()
          );
  }
});

export const EmbBreadcrumbs = defineComponent({
  name: "EmbBreadcrumbs",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "emb-breadcrumbs",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const EmbSkeleton = defineComponent({
  name: "EmbSkeleton",
  props: {
    variant: { type: String as PropType<SkeletonVariant>, default: "line" }
  },
  setup(props, { attrs }) {
    return () =>
          h("emb-skeleton", {
              ...attrs,
              variant: props.variant,
          });
  }
});

export const EmbStepper = defineComponent({
  name: "EmbStepper",
  props: {
    disabled: { type: Boolean, default: false },
    interactive: { type: Boolean, default: false },
    orientation: { type: String as PropType<StepperOrientation>, default: "horizontal" },
    steps: { type: Array as PropType<StepperStep[]>, default: () => [] },
    modelValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-stepper", {
              ...attrs,
              disabled: props.disabled || undefined,
              interactive: props.interactive || undefined,
              orientation: props.orientation,
              steps: props.steps,
              value: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbLink = defineComponent({
  name: "EmbLink",
  props: {
    download: { type: String, default: "" },
    href: { type: String, default: "" },
    rel: { type: String, default: "" },
    target: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-link",
            {
              ...attrs,
              download: props.download || undefined,
              href: props.href || undefined,
              rel: props.rel || undefined,
              target: props.target || undefined,
            },
            slots.default?.()
          );
  }
});

export const EmbFieldset = defineComponent({
  name: "EmbFieldset",
  props: {
    disabled: { type: Boolean, default: false },
    legend: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-fieldset",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              legend: props.legend || undefined,
            },
            slots
          );
  }
});

export const EmbFormField = defineComponent({
  name: "EmbFormField",
  props: {
    description: { type: String, default: "" },
    error: { type: String, default: "" },
    label: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-form-field",
            {
              ...attrs,
              description: props.description || undefined,
              error: props.error || undefined,
              label: props.label || undefined,
              required: props.required || undefined,
            },
            slots
          );
  }
});

export const EmbHelperText = defineComponent({
  name: "EmbHelperText",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "emb-helper-text",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const EmbErrorText = defineComponent({
  name: "EmbErrorText",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "emb-error-text",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const EmbRange = defineComponent({
  name: "EmbRange",
  props: {
    disabled: { type: Boolean, default: false },
    max: { type: Number, default: 100 },
    min: { type: Number, default: 0 },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    step: { type: Number, default: 1 },
    modelValue: { type: Number, default: 0 }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("change", event);
    };
    return () =>
          h("emb-range", {
              ...attrs,
              disabled: props.disabled || undefined,
              max: props.max,
              min: props.min,
              name: props.name || undefined,
              required: props.required || undefined,
              step: props.step,
              value: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbFileInput = defineComponent({
  name: "EmbFileInput",
  props: {
    accept: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    multiple: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:files", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("change", event);
    };
    return () =>
          h("emb-file-input", {
              ...attrs,
              accept: props.accept || undefined,
              disabled: props.disabled || undefined,
              multiple: props.multiple || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbPagination = defineComponent({
  name: "EmbPagination",
  props: {
    currentPage: { type: Number, default: 1 },
    maxVisiblePages: { type: Number, default: 5 },
    totalPages: { type: Number, default: 1 }
  },
  emits: ["update:currentPage", "change"],
  setup(props, { attrs, emit }) {
    const handleChange = (event: Event) => {
      const target = event.currentTarget as PageHost;
      emit("update:currentPage", target.currentPage);
      emit("change", event);
    };
    return () =>
          h("emb-pagination", {
              ...attrs,
              currentPage: props.currentPage,
              maxVisiblePages: props.maxVisiblePages,
              totalPages: props.totalPages,
              onChange: handleChange,
          });
  }
});

export const EmbDataTable = defineComponent({
  name: "EmbDataTable",
  props: {
    caption: { type: String, default: "" },
    columns: { type: Array as PropType<DataTableColumn[]>, default: () => [] },
    currentPage: { type: Number, default: 1 },
    emptyMessage: { type: String, default: "No rows to display." },
    loading: { type: Boolean, default: false },
    pageSize: { type: Number, default: 10 },
    rows: { type: Array as PropType<DataTableRow[]>, default: () => [] },
    searchable: { type: Boolean, default: false },
    searchLabel: { type: String, default: "Search rows" },
    searchPlaceholder: { type: String, default: "Search rows" },
    searchQuery: { type: String, default: "" },
    sortDirection: { type: String as PropType<DataTableSortDirection>, default: "ascending" },
    sortKey: { type: String, default: "" }
  },
  emits: ["update:currentPage", "page-change", "update:searchQuery", "search-change"],
  setup(props, { attrs, emit }) {
    const handlePageChange = (event: Event) => {
      const target = event.currentTarget as PageHost;
      emit("update:currentPage", target.currentPage);
      emit("page-change", event);
    };

    const handleSearchChange = (event: Event) => {
      const target = event.currentTarget as SearchQueryHost;
      emit("update:searchQuery", target.searchQuery);
      emit("search-change", event);
    };
    return () =>
          h("emb-data-table", {
              ...attrs,
              caption: props.caption || undefined,
              columns: props.columns,
              currentPage: props.currentPage,
              emptyMessage: props.emptyMessage,
              loading: props.loading || undefined,
              pageSize: props.pageSize,
              rows: props.rows,
              searchable: props.searchable || undefined,
              searchLabel: props.searchLabel,
              searchPlaceholder: props.searchPlaceholder,
              searchQuery: props.searchQuery || undefined,
              sortDirection: props.sortDirection,
              sortKey: props.sortKey || undefined,
              onPageChange: handlePageChange,
              onSearchChange: handleSearchChange,
          });
  }
});

export const EmbEmptyState = defineComponent({
  name: "EmbEmptyState",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "emb-empty-state",
            {
              ...attrs,
            },
            slots
          );
  }
});

export const EmbIcon = defineComponent({
  name: "EmbIcon",
  props: {
    label: { type: String, default: "" },
    name: { type: String, default: "" },
    size: { type: Number, default: 20 },
    strokeWidth: { type: Number, default: 2 }
  },
  setup(props, { attrs }) {
    return () =>
          h("emb-icon", {
              ...attrs,
              label: props.label || undefined,
              name: props.name || undefined,
              size: props.size,
              strokeWidth: props.strokeWidth,
          });
  }
});

export const EmbCodeBlock = defineComponent({
  name: "EmbCodeBlock",
  props: {
    code: { type: String, default: "" },
    language: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-code-block",
            {
              ...attrs,
              code: props.code || undefined,
              language: props.language || undefined,
            },
            slots.default?.()
          );
  }
});

export const EmbCommandPalette = defineComponent({
  name: "EmbCommandPalette",
  props: {
    commands: { type: Array as PropType<CommandPaletteCommand[]>, default: () => [] },
    emptyMessage: { type: String, default: "No matching commands." },
    modelValue: { type: String, default: "" },
    open: { type: Boolean, default: false },
    placeholder: { type: String, default: "Search commands" },
    query: { type: String, default: "" },
    title: { type: String, default: "Command palette" }
  },
  emits: ["update:modelValue", "input", "change", "update:open", "close", "cancel", "command-select"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };

    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };

    const handleCancel = (event: Event) => {
      emit("update:open", false);
      emit("cancel", event);
    };

    const handleCommandSelect = (event: Event) => {
      emit("command-select", event);
    };
    return () =>
          h("emb-command-palette", {
              ...attrs,
              commands: props.commands,
              "empty-message": props.emptyMessage,
              value: props.modelValue,
              open: props.open || undefined,
              placeholder: props.placeholder,
              query: props.query || undefined,
              title: props.title,
              onInput: handleInput,
              onChange: handleChange,
              onClose: handleClose,
              onCancel: handleCancel,
              onCommandSelect: handleCommandSelect,
          });
  }
});

export const EmbContextMenu = defineComponent({
  name: "EmbContextMenu",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "emb-context-menu",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots
          );
  }
});

export const EmbListbox = defineComponent({
  name: "EmbListbox",
  props: {
    activeIndex: { type: Number, default: -1 },
    multiselectable: { type: Boolean, default: false },
    selectedValue: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-listbox",
            {
              ...attrs,
              activeIndex: props.activeIndex,
              multiselectable: props.multiselectable || undefined,
              selectedValue: props.selectedValue || undefined,
            },
            slots.default?.()
          );
  }
});

export const EmbMenu = defineComponent({
  name: "EmbMenu",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "emb-menu",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const EmbMenuItem = defineComponent({
  name: "EmbMenuItem",
  props: {
    disabled: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-menu-item",
            {
              ...attrs,
              disabled: props.disabled || undefined,
            },
            slots.default?.()
          );
  }
});

export const EmbNumberInput = defineComponent({
  name: "EmbNumberInput",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    step: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-number-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              step: props.step || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbSearch = defineComponent({
  name: "EmbSearch",
  props: {
    autocomplete: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "search" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-search", {
              ...attrs,
              autocomplete: props.autocomplete || undefined,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbSplitter = defineComponent({
  name: "EmbSplitter",
  props: {
    orientation: { type: String as PropType<SplitterOrientation>, default: "horizontal" }
  },
  emits: ["panel-resize"],
  setup(props, { attrs, emit, slots }) {
    const handlePanelResize = (event: Event) => {
      emit("panel-resize", event);
    };
    return () =>
          h(
            "emb-splitter",
            {
              ...attrs,
              orientation: props.orientation,
              onPanelResize: handlePanelResize,
            },
            slots.default?.()
          );
  }
});

export const EmbSplitterPanel = defineComponent({
  name: "EmbSplitterPanel",
  props: {
    minSize: { type: Number, default: 10 },
    size: { type: Number, default: 0 }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-splitter-panel",
            {
              ...attrs,
              "min-size": props.minSize,
              size: props.size,
            },
            slots.default?.()
          );
  }
});

export const EmbSegmentedControl = defineComponent({
  name: "EmbSegmentedControl",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    options: { type: Array as PropType<SegmentedControlOption[]>, default: () => [] },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-segmented-control", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              options: props.options,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbCombobox = defineComponent({
  name: "EmbCombobox",
  props: {
    autocomplete: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "emb-combobox",
            {
              ...attrs,
              autocomplete: props.autocomplete || undefined,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const EmbDateInput = defineComponent({
  name: "EmbDateInput",
  props: {
    disabled: { type: Boolean, default: false },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-date-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbTimeInput = defineComponent({
  name: "EmbTimeInput",
  props: {
    disabled: { type: Boolean, default: false },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    step: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-time-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              step: props.step || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbRatingInput = defineComponent({
  name: "EmbRatingInput",
  props: {
    clearable: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    max: { type: Number, default: 5 },
    modelValue: { type: Number, default: 0 },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("change", event);
    };
    return () =>
          h("emb-rating-input", {
              ...attrs,
              clearable: props.clearable || undefined,
              disabled: props.disabled || undefined,
              max: props.max,
              value: props.modelValue,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbToast = defineComponent({
  name: "EmbToast",
  props: {
    dismissible: { type: Boolean, default: false },
    open: { type: Boolean, default: true },
    tone: { type: String as PropType<"neutral" | "success" | "warning" | "danger">, default: "neutral" }
  },
  emits: ["update:open", "close"],
  setup(props, { attrs, emit, slots }) {
    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };
    return () =>
          h(
            "emb-toast",
            {
              ...attrs,
              dismissible: props.dismissible || undefined,
              open: props.open || undefined,
              tone: props.tone,
              onClose: handleClose,
            },
            slots.default?.()
          );
  }
});

export const EmbToastRegion = defineComponent({
  name: "EmbToastRegion",
  props: {
    maxVisible: { type: Number, default: 5 },
    placement: { type: String as PropType<ToastPlacement>, default: "top-end" }
  },
  emits: ["toast-show", "toast-remove"],
  setup(props, { attrs, emit, slots }) {
    const handleToastShow = (event: Event) => {
      emit("toast-show", event);
    };

    const handleToastRemove = (event: Event) => {
      emit("toast-remove", event);
    };
    return () =>
          h(
            "emb-toast-region",
            {
              ...attrs,
              maxVisible: props.maxVisible,
              placement: props.placement,
              onToastShow: handleToastShow,
              onToastRemove: handleToastRemove,
            },
            slots
          );
  }
});

export const EmbTooltip = defineComponent({
  name: "EmbTooltip",
  props: {
    open: { type: Boolean, default: false },
    text: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-tooltip",
            {
              ...attrs,
              open: props.open || undefined,
              text: props.text || undefined,
            },
            slots.default?.()
          );
  }
});

export const EmbToolbar = defineComponent({
  name: "EmbToolbar",
  props: {
    orientation: { type: String as PropType<ToolbarOrientation>, default: "horizontal" },
    wrap: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-toolbar",
            {
              ...attrs,
              orientation: props.orientation,
              wrap: props.wrap || undefined,
            },
            slots.default?.()
          );
  }
});

export const EmbPopover = defineComponent({
  name: "EmbPopover",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "emb-popover",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots.default?.()
          );
  }
});

export const EmbDropdownMenu = defineComponent({
  name: "EmbDropdownMenu",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "emb-dropdown-menu",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots.default?.()
          );
  }
});

export const EmbDropzone = defineComponent({
  name: "EmbDropzone",
  props: {
    accept: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    multiple: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:files", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("change", event);
    };
    return () =>
          h("emb-dropzone", {
              ...attrs,
              accept: props.accept || undefined,
              disabled: props.disabled || undefined,
              multiple: props.multiple || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbDrawer = defineComponent({
  name: "EmbDrawer",
  props: {
    open: { type: Boolean, default: false },
    side: { type: String as PropType<"start" | "end">, default: "end" }
  },
  emits: ["update:open", "close"],
  setup(props, { attrs, emit, slots }) {
    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };
    return () =>
          h(
            "emb-drawer",
            {
              ...attrs,
              open: props.open || undefined,
              side: props.side,
              onClose: handleClose,
            },
            slots.default?.()
          );
  }
});

export const EmbInput = defineComponent({
  name: "EmbInput",
  props: {
    autocomplete: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    type: { type: String, default: "text" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-input", {
              ...attrs,
              autocomplete: props.autocomplete || undefined,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              type: props.type,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbEmailInput = defineComponent({
  name: "EmbEmailInput",
  props: {
    autocomplete: { type: String, default: "email" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-email-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbPasswordInput = defineComponent({
  name: "EmbPasswordInput",
  props: {
    autocomplete: { type: String, default: "current-password" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-password-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbOption = defineComponent({
  name: "EmbOption",
  props: {
    active: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    label: { type: String, default: "" },
    selected: { type: Boolean, default: false },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-option",
            {
              ...attrs,
              active: props.active || undefined,
              disabled: props.disabled || undefined,
              label: props.label || undefined,
              selected: props.selected || undefined,
              value: props.value || undefined,
            },
            slots.default?.()
          );
  }
});

export const EmbTelInput = defineComponent({
  name: "EmbTelInput",
  props: {
    autocomplete: { type: String, default: "tel" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-tel-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbUrlInput = defineComponent({
  name: "EmbUrlInput",
  props: {
    autocomplete: { type: String, default: "url" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-url-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbColorInput = defineComponent({
  name: "EmbColorInput",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "#4f46e5" },
    name: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-color-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbCheckbox = defineComponent({
  name: "EmbCheckbox",
  props: {
    modelValue: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    value: { type: String, default: "on" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("change", event);
    };
    return () =>
          h(
            "emb-checkbox",
            {
              ...attrs,
              checked: props.modelValue || undefined,
              disabled: props.disabled || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              value: props.value,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const EmbSelect = defineComponent({
  name: "EmbSelect",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as SelectHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as SelectHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "emb-select",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const EmbRadio = defineComponent({
  name: "EmbRadio",
  props: {
    checked: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    value: { type: String, default: "on" }
  },
  emits: ["update:checked", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:checked", target.checked);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:checked", target.checked);
      emit("change", event);
    };
    return () =>
          h(
            "emb-radio",
            {
              ...attrs,
              checked: props.checked || undefined,
              disabled: props.disabled || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              value: props.value,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const EmbDialog = defineComponent({
  name: "EmbDialog",
  props: {
    modal: { type: Boolean, default: true },
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "close", "cancel"],
  setup(props, { attrs, emit, slots }) {
    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };

    const handleCancel = (event: Event) => {
      emit("update:open", false);
      emit("cancel", event);
    };
    return () =>
          h(
            "emb-dialog",
            {
              ...attrs,
              modal: props.modal || undefined,
              open: props.open || undefined,
              onClose: handleClose,
              onCancel: handleCancel,
            },
            slots.default?.()
          );
  }
});

export const EmbTextarea = defineComponent({
  name: "EmbTextarea",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    rows: { type: Number, default: 4 }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("emb-textarea", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              rows: props.rows,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const EmbSwitch = defineComponent({
  name: "EmbSwitch",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    value: { type: String, default: "on" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("change", event);
    };
    return () =>
          h(
            "emb-switch",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              checked: props.modelValue || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              value: props.value,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const EmbTabs = defineComponent({
  name: "EmbTabs",
  props: {
    value: { type: String, default: "" }
  },
  emits: ["update:value", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleChange = (event: Event) => {
      const target = event.currentTarget as SelectHost;
      emit("update:value", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "emb-tabs",
            {
              ...attrs,
              value: props.value || undefined,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const EmbAccordion = defineComponent({
  name: "EmbAccordion",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "emb-accordion",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots.default?.()
          );
  }
});

export const EmbTreeItem = defineComponent({
  name: "EmbTreeItem",
  props: {
    disabled: { type: Boolean, default: false },
    expanded: { type: Boolean, default: false },
    label: { type: String, default: "" },
    selected: { type: Boolean, default: false },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "emb-tree-item",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              expanded: props.expanded || undefined,
              label: props.label || undefined,
              selected: props.selected || undefined,
              value: props.value || undefined,
            },
            slots
          );
  }
});

export const EmbTreeView = defineComponent({
  name: "EmbTreeView",
  props: {
    modelValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "emb-tree-view",
            {
              ...attrs,
              value: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});
