export const versionFiles: string[];
export const exemptNonVersionFiles: string[];
export const docsOnlyFilePrefixes: string[];
export const docsOnlyFiles: string[];
export const workspacePackageFiles: string[];

export function getChangedFiles(base: string, head?: string): string[];
export function resolveDiffBase(base: string, head?: string): string;
export function getChangedNonVersionFiles(changedFiles: string[]): string[];
export function isDocsOnlyFile(file: string): boolean;
export function getChangedReleaseRelevantFiles(changedFiles: string[]): string[];
export function readJson<T = unknown>(filePath: string): T;
export function writeJson(filePath: string, value: unknown): void;
export function readGitJson<T = unknown>(ref: string, filePath: string): T;
export function toGitPath(filePath: string): string;
export function compareVersions(left: string, right: string): number;
export function incrementVersion(version: string, level?: "major" | "minor" | "patch"): string;
export function syncWorkspaceVersions(version: string): void;
export function getHighestWorkspaceVersion(): string | undefined;
export function parseVersion(version: string): { major: number; minor: number; patch: number; prerelease: string };
export function isZeroSha(value: string): boolean;
export function fail(message: string): never;
